### ISSUE TITLE
Not able to run the Program

### ISSUE THREAD

**Issue by pavchavan** [Kawaian/OpenPoseSharp#1]
Not able to run the Program.

Getting the error as:
System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'OpenPoseSharp.OpenPosePINVOKE' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at OpenPoseSharp.OpenPosePINVOKE.new_IntPoint__SWIG_0(Int32 jarg1, Int32 jarg2)
   at OpenPoseSharp.IntPoint..ctor(Int32 x, Int32 y) in C:\Users\admin\Downloads\OpenPoseSharp-master (1)\OpenPoseSharp-master\src\swig\genSwig\IntPoint.cs:line 63
   at OpenPoseSharp.Test.Windows.HandLandmarkDetector.Init() in C:\Users\admin\Downloads\OpenPoseSharp-master (1)\OpenPoseSharp-master\src\OpenPoseSharp.Test.Windows\Program.cs:line 73
   at OpenPoseSharp.Test.Windows.Program.Main(String[] args) in C:\Users\admin\Downloads\OpenPoseSharp-master (1)\OpenPoseSharp-master\src\OpenPoseSharp.Test.Windows\Program.cs:line 141

Inner Exception 1:
TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.

Inner Exception 2:
EntryPointNotFoundException: Unable to find an entry point named 'SWIGRegisterExceptionCallbacks_OpenPose' in DLL 'OpenPose'.

please help me out .

**Comment by pavchavan** [comment]
is there any specific way to build the Openpose dll for this wraper to work?
